### ISSUE TITLE
Python cuda methods not working despite BUILD_VGICP_CUDA=ON

### ISSUE THREAD

**Issue by AndreejS** [SMRT-AIST/fast_gicp#100]
Hey,
I have build everything as mentioned in the Non-ROS section of the README with -DBUILD_VGICP_CUDA=ON and applied what was mentioned in #66 to create the python bindings. GICP and VGICP are working without any issues, however for the CUDA methods (VGICP_CUDA and NDT_CUDA) i get "**error: you need to build fast_gicp with BUILD_VGICP_CUDA=ON**" and receive the identity as a result.

I verified that the build was successful with CUDA:
![Cuda-Build](https://user-images.githubusercontent.com/39523653/181911382-49d73925-d197-436f-ac78-91f13709a394.png)
As well as verifying that all cuda based folders within gicp are created afterwards.

Additionally i checked if there is any issue with CUDA:
![deviceQuery](https://user-images.githubusercontent.com/39523653/181911820-01e074d0-af24-4cbb-9fbe-2079f6f2ed78.png)

Everything was done on Ubuntu 18.04 with Python 3.9.
I would be grateful for any hints to solve this.

**Comment by AndreejS** [comment]
For those who experience the same issue, it can be fixed by enabling "BUILD_VGICP_CUDA" in the Python bindings, [here](https://github.com/SMRT-AIST/fast_gicp/blob/master/setup.py#L51). 

Since the CUDA approaches are disabled by default in python and "cmake ... -DCMAKE_BUILD_TYPE=Release -DBUILD_VGICP_CUDA=ON" will obviously not fix this.

**Comment by Zhao-hangtian** [comment]
how to config fastgcpi to use CUDA in python? please
