### ISSUE TITLE
run in other platform

### ISSUE THREAD

**Issue by whuzs** [SMRT-AIST/fast_gicp#107]
pcl 1.10.0
orin aarch64
eigen 3.4.0
cuda 11.4

i found ndtcuda get nan result

**Comment by whuzs** [comment]
i run it in cuda11.4/orin, but eigen in cuda is not working

**Comment by whuzs** [comment]
some worning is:
./modules/localization/zj/third_party/Eigen3/Eigen/src/Core/AssignEvaluator.h(862): warning: calling a __host__ function("Eigen::internal::Assignment< ::Eigen::Matrix<float, (int)3, (int)3, (int)0, (int)3, (int)3> ,  ::Eigen::DiagonalWrapper<const  ::Eigen::Matrix<float, (int)3, (int)1, (int)0, (int)3, (int)1> > ,  ::Eigen::internal::assign_op<float, float> ,  ::Eigen::internal::Diagonal2Dense, void> ::run( ::Eigen::Matrix<float, (int)3, (int)3, (int)0, (int)3, (int)3>  &, const  ::Eigen::DiagonalWrapper<const  ::Eigen::Matrix<float, (int)3, (int)1, (int)0, (int)3, (int)1> >  &, const  ::Eigen::internal::assign_op<float, float>  &)") from a __host__ __device__ function("Eigen::internal::call_assignment_no_alias< ::Eigen::Matrix<float, (int)3, (int)3, (int)0, (int)3, (int)3> ,  ::Eigen::DiagonalWrapper<const  ::Eigen::Matrix<float, (int)3, (int)1, (int)0, (int)3, (int)1> > ,  ::Eigen::internal::assign_op<float, float> > ") is not allowed

**Comment by whuzs** [comment]
some warning is:
warning: calling a __host__ function("Eigen::internal::Assignment< ::Eigen::Matrix<float, (int)3, (int)3, (int)0, (int)3, (int)3> ,  ::Eigen::DiagonalWrapper<const  ::Eigen::Matrix<float, (int)3, (int)1, (int)0, (int)3, (int)1> > ,  ::Eigen::internal::assign_op<float, float> ,  ::Eigen::internal::Diagonal2Dense, void> ::run( ::Eigen::Matrix<float, (int)3, (int)3, (int)0, (int)3, (int)3>  &, const  ::Eigen::DiagonalWrapper<const  ::Eigen::Matrix<float, (int)3, (int)1, (int)0, (int)3, (int)1> >  &, const  ::Eigen::internal::assign_op<float, float>  &)") from a __host__ __device__ function("Eigen::internal::call_assignment_no_alias< ::Eigen::Matrix<float, (int)3, (int)3, (int)0, (int)3, (int)3> ,  ::Eigen::DiagonalWrapper<const  ::Eigen::Matrix<float, (int)3, (int)1, (int)0, (int)3, (int)1> > ,  ::Eigen::internal::assign_op<float, float> > ") is not allowed

**Comment by whuzs** [comment]
host__ function("Eigen::internal::all_unroller< ::Eigen::internal::evaluator< ::Eigen::CwiseBinaryOp<    ::std::equal_to<int> , const  ::Eigen::Matrix<int, (int)3, (int)1, (int)0, (int)3, (int)1> , const  ::Eigen::Matrix<int, (int)3, (int)1, (int)0, (int)3, (int)1> > > , (int)3, (int)3> ::run(const  ::Eigen::internal::evaluator< ::Eigen::CwiseBinaryOp<    ::std::equal_to<int> , const  ::Eigen::Matrix<int, (int)3, (int)1, (int)0, (int)3, (int)1> , const  ::Eigen::Matrix<int, (int)3, (int)1, (int)0, (int)3, (int)1> > >  &)") from a __host__ __device__ function("Eigen::DenseBase< ::Eigen::CwiseBinaryOp<    ::std::equal_to<int> , const  ::Eigen::Matrix<int, (int)3, (int)1, (int)0, (int)3, (int)1> , const  ::Eigen::Matrix<int, (int)3, (int)1, (int)0, (int)3, (int)1> > > ::all const") is not allowed

**Comment by whuzs** [comment]
![image](https://user-images.githubusercontent.com/38743240/204214615-6b1ee5f8-aac5-4ffa-9e29-86081894dba8.png)

**Comment by whuzs** [comment]
had fixed, because of ndt cov regularization(asDiagonal), but donot know why

**Comment by EniProgettiTommasoBorzone** [comment]
Hi, 

we are experiencing exactly the same problem on an equivalent system:
- pcl 1.10
- aarch64 (jetson xavier NX)
- eigen 3.4.0
- cuda 11.4

There is an assertion fail because of nan cloud input.

Can you share the fix please?

Thnak you very much.

**Comment by qpc001** [comment]
> Hi,
> 
> 你好，
> 
> we are experiencing exactly the same problem on an equivalent system:
> 
> 我们在等效系统上遇到了完全相同的问题：
> 
> * pcl 1.10 聚合酶链反应1.10
> * aarch64 (jetson xavier NX) aarch64（喷气式飞机xavier NX）
> * eigen 3.4.0 特征值3.4.0
> * cuda 11.4 CUDA 11.4
> 
> There is an assertion fail because of nan cloud input.
> 
> 由于nan云输入，存在断言失败。
> 
> Can you share the fix please?
> 
> 你能分享一下吗？
> 
> Thnak you very much.
> 
> 非常感谢。

Checkout this pull request #112 and try it.
