### ISSUE TITLE
lm not converged!!

### ISSUE THREAD

**Issue by improve100** [SMRT-AIST/fast_gicp#109]
I plan to compare the results of fast gicp matching, 
but I find that the results in my dataset are not very good, and there are problems with convergence. 
Please help me analyze the reasons. 
target:513658[pts] source:12879[pts]
--- fgicp_st ---
setinputtarget time:224.558[msec]
single:4930.35[msec] fitness_score:4.94828
--- fgicp_mt ---
setinputtarget time:216.625[msec]
single:970.577[msec] fitness_score:4.95613
--- vgicp_st ---
setinputtarget time:232.753[msec]
single:3645.91[msec] fitness_score:5.14035
--- vgicp_mt ---
setinputtarget time:241.628[msec]
single:832.951[msec] fitness_score:5.14035
--- vgicp_cuda (parallel_kdtree) ---
setinputtarget time:449.569[msec]
lm not converged!!
single:325.198[msec] fitness_score:5.18139
--- vgicp_cuda (gpu_bruteforce) ---
setinputtarget time:7665.43[msec]
single:323.909[msec] fitness_score:6.46557
--- vgicp_cuda (gpu_rbf_kernel) ---
setinputtarget time:8621.8[msec]
lm not converged!!
single:303.051[msec] fitness_score:4.98786
Here is my test set:
[test.zip](https://github.com/SMRT-AIST/fast_gicp/files/10323531/test.zip)

**Comment by koide3** [comment]
Does the problem happen with only GPU-based methods?

**Comment by improve100** [comment]
Yes,but I focus on GPU-based.

**Comment by koide3** [comment]
I'm not sure but the cause can be that the target has too many points. The GPU implementations use single-precision floating points for fast computation and can suffer from a large mount of points. Try downsampling or cropping to reduce the number of points.

**Comment by improve100** [comment]
Thanks for your advice. I'll try it.
