### ISSUE TITLE
Example of exporting results for evaluation?

### ISSUE THREAD

**Issue by espackman-nv** [SMRT-AIST/fast_gicp#115]
Hi! I am excited by your work, and am interested in using your algorithms as part of a Python project.
I am using this repo to perform evaluations of ICP algorithms on the KITTI benchmark suite:  https://github.com/Huangying-Zhan/kitti-odom-eval.
Is there an existing method of exporting the poses, such as the ones generated in the Kitti.py script? I could try to make one myself, but I don't want any errors on my part to affect the results. Thank you!

**Comment by koide3** [comment]
No, this package does not provide any trajectory exporting functions. Note that ```kitti.py``` is just an example code to show the basic usage, and you may need  to tune the parameters by yourself.

**Comment by espackman-nv** [comment]
Thanks for the answer!
