### ISSUE TITLE
[question] How would I go about optimizing < 6 pose parameters?

### ISSUE THREAD

**Issue by themightyoarfish** [SMRT-AIST/fast_gicp#121]
I don't know much about optimization, but with PCL and LM optimization, one can use warp functions (e.g. https://pointclouds.org/documentation/classpcl_1_1registration_1_1_warp_point_rigid3_d.html)  to limit the degrees of freedom to optimize. This code is also using LM, so what would one need to do to e.g. only optimize translation?
Is it just a matter of changing the 6x6 and 6x1 matrices in the process to nxn and nx1 and change the code that turns the parameters into a transform? Or are there any pitfalls.

Would the same work for GN?

**Comment by themightyoarfish** [comment]
related but potentially different: https://github.com/SMRT-AIST/fast_gicp/issues/104

**Comment by koide3** [comment]
You can do the same way as #104 or give H[3:, 3:] and b[3:] to the linear solver. Both the ways should work for GN and LM.

https://github.com/SMRT-AIST/fast_gicp/blob/4d8ef99378b099269d82c51ed4b16f9dff922706/include/fast_gicp/gicp/impl/lsq_registration_impl.hpp#L136

**Comment by themightyoarfish** [comment]
Thanks, i will try this.
