### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by tiesus** [SMRT-AIST/fast_gicp#124]
I try to compile the code under Ubuntu 20.04 with CUDA 12. 

The following error occurs: 
`/catkin_ws/src/fast_gicp/src/fast_gicp/cuda/brute_force_knn.cu:9:10: fatal error: nvbio/basic/vector_view.h: No such file or directory
    9 | #include <nvbio/basic/vector_view.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
`

Must `nvbio` be installed from source? Is it maybe possible to update the compile instructions?

**Comment by bilibilicharger** [comment]
DId you solve this problem？

**Comment by tiesus** [comment]
No, unfortunately not. Switched to another icp implementation.
