### ISSUE TITLE
scan matching has not converged!!

### ISSUE THREAD

**Issue by liuyf5231** [SMRT-AIST/fast_gicp#14]
hi,
I change the registration method of hdl graph slam to fast gicp ,  but the registration method may be not converged!
![1](https://user-images.githubusercontent.com/47884441/80440973-6a23de00-893c-11ea-8781-5bd4bdd392dc.png)

**Comment by liuyf5231** [comment]
another bug,
`matching.Sophus ensure failed in function 'Sophus::SO3<Scalar_, Options>::SO3(const Transformation&) [with Scalar_ = float; int Options = 0; Sophus::SO3<Scalar_, Options>::Transformation = Eigen::Matrix<float, 3, 3>]', file '/..../src/fast_gicp/thirdparty/Sophus/sophus/so3.hpp', line 473.
R is not orthogonal:
      1.00001 -1.83471e-07 -1.13947e-06
-1.83471e-07      1.00001  4.81601e-07
-1.13947e-06  4.81601e-07 `

**Comment by hitbg-yjm** [comment]
How do you solve the problem？ we have the same problem.

**Comment by koide3** [comment]
This error happens when the rotation part of the initial guess is not orthogonal. A workaround is to do normalize the initial guess like:
```cpp
Eigen::Matrix4d initial_guess = ...;
initial_guess.block<3, 3>(0, 0) = Eigen::Quaterniond(initial_guess.block<3, 3>(0, 0)).normalized().toRotationMatrix();
gicp.align(aligned_cloud, inigial_guess.cast<float>());
```

**Comment by hitbg-yjm** [comment]
> This error happens when the rotation part of the initial guess is not orthogonal. A workaround is to do normalize the initial guess like:
> 
> ```c++
> Eigen::Matrix4d initial_guess = ...;
> initial_guess.block<3, 3>(0, 0) = Eigen::Quaterniond(initial_guess.block<3, 3>(0, 0)).normalized().toRotationMatrix();
> gicp.align(aligned_cloud, inigial_guess.cast<float>());
> ```

Thank you for your response.  I will try this way ,it helps a lot.

**Comment by gulfemakpinar** [comment]
I am using FastVGICP and I faced with the same  problem. Could you help me?
