### ISSUE TITLE
Why is the **weight** the square root of the number of points?

### ISSUE THREAD

**Issue by QiMingZhenFan** [SMRT-AIST/fast_gicp#147]
Firstly, Thanks for the contribution!!

According to this [line](https://github.com/SMRT-AIST/fast_gicp/blob/master/include/fast_gicp/gicp/impl/fast_vgicp_impl.hpp#L149), for each correspondence, we multiply a weight to the error, whose value is the **square root** of the number of points in the corresponding voxel. 

`double w = std::sqrt(target_voxel->num_points);`

However, in the thesis _**Voxelized GICP for Fast and Accurate 3D Point Cloud Registration**_, the equation (11) indicates that the weight should be the number of voxel points, **not the square root**, as shown in the following figure.
![screenshot-20240201-182159](https://github.com/SMRT-AIST/fast_gicp/assets/38323127/74d3afcb-738c-45e4-a176-8cb687e79099)

I am confused by this. Are there any special considerations in the code?

**Comment by koide3** [comment]
Ah, it may be contaminated from other formulations I had been trying. Using `w` without sqrt should be correct. Note that I found that `w` has only a small effect as long as the spatial density of points is more or less uniform.

**Comment by koide3** [comment]
Yes, I meant unless a voxel has 10x or more points than other voxels, the effect of w is small. In many cases, you can just ignore it.
