### ISSUE TITLE
the processing timing too large in some frame

### ISSUE THREAD

**Issue by DarrenWong** [SMRT-AIST/fast_gicp#17]
Dear officer,

I integrated the fast_gicp into hdl_slam by adding the methods into registration.cpp, very impressive compare to the original gicp in terms of processing time. 
But I fount in some frame it appears larger processing time(more than 1s ) which might reduce the accuracy of odometry if I try to run the method in real-time

Record processing timing of matching function in the  below function
 `  Eigen::Matrix4f pose = matching(cloud_msg->header.stamp, cloud);`
https://github.com/koide3/hdl_graph_slam/blob/0228e86b7f4f9649515b0217440694bc1fdf7f20/apps/scan_matching_odometry_nodelet.cpp#L113

Running with ubuntu18.04 with ROS melodic, CUDA 10.2 with Nvidia GeForce GTX 1660Ti. 
FastGICP(max: 1465.45 ms), Fast VGICP(max 1156.91ms) and  FastVGICPCuda(max 1626.14ms)  have similar results after a few repeat trying with our bag files. 
The bag file:  
https://www.dropbox.com/s/pfjvauvletdpnh2/2019-04-28-20-58-02.bag?dl=0
https://www.polyu-ipn-lab.com/download  
(playback speed: FastGICP r=0.5, Fast VGICP r =1, FastVGICPCuda r =1)

Take FastVGICPCuda's processing time (in ms) as an example:

25.238248
26.579396
46.928215
27.55004
32.815564
1255.325887
31.012012
30.705918
19.767951
24.523302
28.338081
30.295409
33.668795

![image](https://user-images.githubusercontent.com/5771106/86573517-13272e80-bfa7-11ea-8117-73f8b986a9ee.png)
max:1626.14/ min16.03/ mean 38.08/ median 31.28

My question is:
Is it an expected result in terms of processing time?  or some mismatch of the bag files with the fast_gicp (I ran the bag file with GICP with max 520.10 ms, playback speed 0.1 )

**Comment by koide3** [comment]
@DarrenWong 
Thanks for letting me know the issue. It's strange that the processing time varies so much and sometimes takes a second for one frame. I'll take a look at your rosbag to find the cause.

**Comment by DarrenWong** [comment]
many thanks for taking your time @koide3 , can you repeat my experiments?

**Comment by koide3** [comment]
Yes, I confirmed the reported behavior on my PC. I need a bit more time to dig into the problem.

![vgicp_cuda_time](https://user-images.githubusercontent.com/31344317/87239983-0d6e9480-c450-11ea-8f34-5a7bda8bd541.png)
VGICP_CUDA time

**Comment by koide3** [comment]
I guess the problem stems from the large number of input points. With voxelgrid resolution = 0.1, the number of of points becomes about 25k in average. It's a bit too much for scan matching, and the gauss newton optimizer can suffer from such many input points. By setting the resolution to 0.25 (or larger), the number of points becomes less than 15k points, and in this settings, I didn't see the problem.

Maybe we need a more stable optimizer (e.g., LM). I would implement it if I could find enough spare time.

**Comment by DarrenWong** [comment]
Got it and thansk for your reply.  LM optimizer shall be better than gauss newton  theoretically.
One more question, how can I set the voxelgrid resolution? I integrated the fast-gicp in hdl_slam with below registration method in here.  https://github.com/koide3/hdl_graph_slam/blob/701a39e17e2be6d39261b5f27e0d1df993efbc99/src/hdl_graph_slam/registrations.cpp#L36
```

if(registration_method.find("VCUDA") != std::string::npos){
      std::cout << "registration: GICP_VGICP" << std::endl;
      boost::shared_ptr<fast_gicp::FastVGICPCuda<PointT, PointT>> gicp(new fast_gicp::FastVGICPCuda<PointT, PointT>());
      gicp->setResolution(1.0);
      return gicp;
    }
```
I default set it 1.0 (is it means voxelgrid resolution = 0.1? ), I try to change to 3.0,  but seems worser. 
![image](https://user-images.githubusercontent.com/5771106/87269668-79103a80-c500-11ea-9c96-bf21b53a4a68.png)

**Comment by koide3** [comment]
There is a nodelet that is in charge of voxelgrid downsampling. You can change ```downsample_resolution``` at the following line:
https://github.com/koide3/hdl_graph_slam/blob/701a39e17e2be6d39261b5f27e0d1df993efbc99/launch/hdl_graph_slam_400.launch#L28

**Comment by DarrenWong** [comment]
I changed the    ` <param name="downsample_resolution" value="0.3" />` to 0.3.
Yes, the processing time is fast but still appears some processing time too large.
I think the root cause is the iteration too long in some frame which contains numerous cars or initial guess not well...  
I agree that a stable optimizer would be better. Thanks for your helping!

![image](https://user-images.githubusercontent.com/5771106/87382275-22226800-c5c9-11ea-8908-d8c62a2a4397.png)


MEDIAN 13.24 / MEAN 15.60 / 1002.834822
