### ISSUE TITLE
Hello, I’m very curious, why is the result of execution different from 100 times?

### ISSUE THREAD

**Issue by hunkyu** [SMRT-AIST/fast_gicp#18]
0.999882  -0.0152821  0.00142344   -0.495192
  0.0152735    0.999866  0.00585251   -0.136181
-0.00151269 -0.00583008    0.999982   0.0277126
          0           0           0           1
   0.999886   0.0150565 -0.00145653    0.500585
  -0.015065    0.999869 -0.00596729    0.124684
 0.00136649  0.00598855    0.999981  -0.0288469
          0           0           0           1
   0.999882  -0.0152818  0.00142326   -0.495191
  0.0152732    0.999866  0.00585304    -0.13619
-0.00151251 -0.00583061    0.999982   0.0277164
          0           0           0           1
   0.999886   0.0150566 -0.00145653    0.500586
  -0.015065    0.999869 -0.00596728    0.124684
  0.0013665  0.00598854    0.999981  -0.0288469
          0           0           0           1
   0.999882  -0.0152803  0.00142338   -0.495188
  0.0152718    0.999866  0.00583876   -0.136183
 -0.0015124 -0.00581633    0.999982   0.0277216
          0           0           0           1
   0.999886   0.0150565 -0.00145653    0.500585
  -0.015065    0.999869 -0.00596728    0.124684
 0.00136649  0.00598854    0.999981  -0.0288469
          0           0           0           1
   0.999882  -0.0152828  0.00142324   -0.495191
  0.0152742    0.999866  0.00585421   -0.136192
-0.00151252 -0.00583179    0.999982   0.0277111
          0           0           0           1
   0.999886   0.0150565 -0.00145653    0.500585
  -0.015065    0.999869 -0.00596727    0.124684
 0.00136649  0.00598853    0.999981  -0.0288469
          0           0           0           1
   0.999882   -0.015282  0.00142347   -0.495192
  0.0152734    0.999866  0.00585232   -0.136179
-0.00151272 -0.00582989    0.999982   0.0277121
          0           0           0           1
   0.999886   0.0150565 -0.00145652    0.500585
  -0.015065    0.999869 -0.00596727    0.124684
 0.00136649  0.00598853    0.999981  -0.0288469
          0           0           0           1
   0.999882  -0.0152802  0.00142369   -0.495187
  0.0152716    0.999866  0.00583821   -0.136181
-0.00151271 -0.00581578    0.999982   0.0277311
          0           0           0           1
   0.999886   0.0150566 -0.00145654    0.500585
  -0.015065    0.999869 -0.00596723    0.124684
  0.0013665  0.00598849    0.999981  -0.0288473
          0           0           0           1
   0.999882   -0.015282  0.00142347   -0.495192
  0.0152735    0.999866  0.00585235    -0.13618
-0.00151271 -0.00582992    0.999982   0.0277117
          0           0           0           1
   0.999886   0.0150587 -0.00145659    0.500592
 -0.0150671    0.999869 -0.00596486    0.124693
 0.00136657  0.00598612    0.999981  -0.0288498
          0           0           0           1
   0.999882   -0.015283  0.00142336   -0.495188
  0.0152745    0.999866  0.00585429   -0.136186
-0.00151264 -0.00583186    0.999982   0.0277165
          0           0           0           1
   0.999886   0.0150565 -0.00145653    0.500585
  -0.015065    0.999869 -0.00596727    0.124684
 0.00136649  0.00598853    0.999981  -0.0288469
          0           0           0           1
   0.999882  -0.0152803  0.00142337   -0.495187
  0.0152718    0.999866  0.00583879   -0.136182
 -0.0015124 -0.00581636    0.999982   0.0277216
          0           0           0           1
   0.999886   0.0150566 -0.00145654    0.500585
  -0.015065    0.999869 -0.00596725    0.124684
  0.0013665  0.00598851    0.999981  -0.0288471
          0           0           0           1
   0.999882   -0.015282  0.00142351   -0.495192
  0.0152734    0.999866  0.00585235   -0.136178
-0.00151276 -0.00582992    0.999982   0.0277156
          0           0           0           1
   0.999886   0.0150583 -0.00145695    0.500587
 -0.0150667    0.999869 -0.00596744    0.124683
  0.0013669  0.00598871    0.999981  -0.0288314
          0           0           0           1
   0.999882  -0.0152866  0.00142242   -0.495196
  0.0152781    0.999866  0.00584714   -0.136171
-0.00151162 -0.00582472    0.999982   0.0277106
          0           0           0           1
   0.999886   0.0150566 -0.00145653    0.500585
  -0.015065    0.999869 -0.00596729    0.124684
 0.00136649  0.00598855    0.999981  -0.0288469
          0           0           0           1
   0.999882  -0.0152818  0.00142326   -0.495191
  0.0152732    0.999866  0.00585296   -0.136189
-0.00151252 -0.00583054    0.999982   0.0277163
          0           0           0           1
   0.999886   0.0150565 -0.00145653    0.500585
  -0.015065    0.999869 -0.00596727    0.124684
 0.00136649  0.00598853    0.999981  -0.0288469
          0           0           0           1
   0.999882  -0.0152821  0.00142346   -0.495192
  0.0152735    0.999866  0.00585235    -0.13618
-0.00151271 -0.00582991    0.999982   0.0277117
          0           0           0           1
   0.999886   0.0150583 -0.00145695    0.500587
 -0.0150667    0.999869 -0.00596744    0.124683
  0.0013669  0.00598871    0.999981  -0.0288313
          0           0           0           1
   0.999882  -0.0152818  0.00142327   -0.495191
  0.0152732    0.999866  0.00585299    -0.13619
-0.00151253 -0.00583056    0.999982   0.0277169
          0           0           0           1
100times_reuse:6893.68[msec] fitness_score:0.0905329

=========================================================
1 times_reuse:90.8963[msec] fitness_score:0.206262
--- vgicp_st ---
   0.999886   0.0150565 -0.00145653    0.500585
  -0.015065    0.999869 -0.00596727    0.124684
 0.00136649  0.00598853    0.999981  -0.0288469
          0           0           0           1
1 times_reuse:122.578[msec] fitness_score:0.207399
--- vgicp_mt ---
   0.999886   0.0150566 -0.00145654    0.500586
  -0.015065    0.999869 -0.00596722    0.124683
 0.00136651  0.00598848    0.999981  -0.0288474
          0           0           0           1
1 times_reuse:61.292[msec] fitness_score:0.207399

**Comment by koide3** [comment]
The difference stems from a multi-threaded loop. With OpenMP, the execution order of the loop can be changed, and floating points summed up in different orders can have different results due to rounding errors. (the difference is very small usually)

**Comment by hunkyu** [comment]
@koide3 I used the demo you gave. The fitness score after one execution and the fitness score after 100 executions are very different. I saw that the input pose is the same, and the initial value does not change as the number of iterations increases. It is currently believed that the smaller the fitness score, the better the registration effect

**Comment by koide3** [comment]
To imitate odometry calculation in which we can reuse precomputed covariances, ```100times_reuse``` performs frame A-to-B and B-to-A registrations alternately. The last result of ```100_times_reuse``` is about frame B-to-A while the other ones are about A-to-B. You can notice the transformations estimated in ```100_time_reuse``` alternately change.

https://github.com/SMRT-AIST/fast_gicp/blob/c5fa2a103d6c345d4fbd24f31f7ec4a2f20115af/src/align.cpp#L83

**Comment by hunkyu** [comment]
@koide3 I get it, thank!
