### ISSUE TITLE
Sophus version

### ISSUE THREAD

**Issue by narutojxl** [SMRT-AIST/fast_gicp#19]
Hi @koide3,
What's the dependency lib `Sophus` version and branch?  Did you use master branch default, could you please give some advice 
about this to build fast_icp on ubuntu16.04?
Thanks for your help!
Jiao

**Comment by koide3** [comment]
Hi @narutojxl ,
We used ```Sophus @ d63ad09``` in ```thirdparty``` directory. I suppose this package can be built on Ubuntu 16.04 (I've not tested it on Ubuntu16 though)
https://github.com/SMRT-AIST/fast_gicp/tree/master/thirdparty

**Comment by narutojxl** [comment]
Hi @koide3 , thanks for your help!!!
I am a  foolish guy, not see the `thirdparty` directory,  rather to dirctly  build the `Sophus` and `nvbio` from source, meet some build errors, spent an afternoon :(
BTW,  according to your build tutorial, meet this error(my cuda is 9.0): 
>
	CMake Error at fast_vgicp_cuda_generated_fast_vgicp_cuda.cu.o.Release.cmake:220 (message):
	  Error generating
	  /home/jxl/jxl_ws/build/fast_gicp/CMakeFiles/fast_vgicp_cuda.dir/src/fast_gicp/cuda/./fast_vgicp_cuda_generated_fast_vgicp_cuda.cu.o


	fast_gicp/CMakeFiles/fast_vgicp_cuda.dir/build.make:83: recipe for target 'fast_gicp/CMakeFiles/fast_vgicp_cuda.dir/src/fast_gicp/cuda/fast_vgicp_cuda_generated_fast_vgicp_cuda.cu.o' failed
	make[2]: *** [fast_gicp/CMakeFiles/fast_vgicp_cuda.dir/src/fast_gicp/cuda/fast_vgicp_cuda_generated_fast_vgicp_cuda.cu.o] Error 1
	CMakeFiles/Makefile2:1391: recipe for target 'fast_gicp/CMakeFiles/fast_vgicp_cuda.dir/all' failed
	make[1]: *** [fast_gicp/CMakeFiles/fast_vgicp_cuda.dir/all] Error 2
	make[1]: *** 正在等待未完成的任务....

**Comment by narutojxl** [comment]
comment about cuda in CMakeLists.txt, then catkin_make, [the same problem](https://github.com/strasdat/Sophus/issues/187#issuecomment-663408601) about sophus and eigen version seems not match, my eigen is 3.2.92 on ubuntu16.04, i will try on ubuntu18.04, where it is eigen3.3.7

**Comment by narutojxl** [comment]
On ubuntu18.04, with cuda 10.0 and system's eigen3.3.7, build successfully(not comment cuda in CMakeLists.txt).
