### ISSUE TITLE
how to see the output?

### ISSUE THREAD

**Issue by AndreV84** [SMRT-AIST/fast_gicp#23]
Hi @koide3
We were able to build & Run the tool on existent pcd files
However, the execution won't create any output files, will it?
```
 rosrun fast_gicp gicp_align points-2.pcd  points-3.pcd
target:79[pts] source:79[pts]
--- pcl_gicp ---
single:2.38397[msec] 100times:219.636[msec] fitness_score:0.019277
--- pcl_ndt ---
single:10.1059[msec] 100times:991.808[msec] fitness_score:0.0203081
--- fgicp_st ---
single:9.13514[msec] 100times:886.917[msec] 100times_reuse:713.189[msec] fitness_score:0.0318018
--- fgicp_mt ---
single:17.7897[msec] 100times:285.958[msec] 100times_reuse:228.059[msec] fitness_score:0.0674881
--- vgicp_st ---
single:1.37252[msec] 100times:108.937[msec] 100times_reuse:92.5806[msec] fitness_score:0.0752508
--- vgicp_mt ---
single:4.60711[msec] 100times:62.8587[msec] 100times_reuse:81.8901[msec] fitness_score:0.0710234
--- vgicp_cuda (parallel_kdtree) ---
single:4.59491[msec] 100times:378.733[msec] 100times_reuse:652.478[msec] fitness_score:0.0831286
--- vgicp_cuda (gpu_bruteforce) ---
single:4.03216[msec] 100times:373.5[msec] 100times_reuse:573.646[msec] fitness_score:0.083081

```

**Comment by AndreV84** [comment]
how to run the ktti example? where to get a dataset?

**Comment by PerceptMD** [comment]
Maybe you should start learning about Point Cloud Library first. PCL has a really nice Point Cloud Viewer.

**Comment by AndreV84** [comment]
@PerceptMD Thank you for your response.
However, could you clarify if the fast_gicp could output a pcd file that could be played by Point Clooud Viewer [PCV}?
On execution of fast gicp it shows benchmarks in the command line. How to get output file to play it in the PCV?

**Comment by qiuxiangrui** [comment]
@AndreV84  Hi,have you resolved this problem? I have the same questions.

**Comment by AndreV84** [comment]
we just used to find other software
with fast_gicp may be other knowledgeable folks will add on how to vizualize

**Comment by qiuxiangrui** [comment]
Thank you. have you run the kitti example successfully  by the fast_gicp which gived by  SMRT-AIST?

**Comment by AndreV84** [comment]
negative
