### ISSUE TITLE
R is not orthogonal

### ISSUE THREAD

**Issue by gulfemakpinar** [SMRT-AIST/fast_gicp#25]
another bug,
`matching.Sophus ensure failed in function 'Sophus::SO3<Scalar_, Options>::SO3(const Transformation&) [with Scalar_ = float; int Options = 0; Sophus::SO3<Scalar_, Options>::Transformation = Eigen::Matrix<float, 3, 3>]', file '/..../src/fast_gicp/thirdparty/Sophus/sophus/so3.hpp', line 473.
R is not orthogonal:
      1.00001 -1.83471e-07 -1.13947e-06
-1.83471e-07      1.00001  4.81601e-07
-1.13947e-06  4.81601e-07 `

_Originally posted by @liuyf5231 in https://github.com/SMRT-AIST/fast_gicp/issue_comments/620425420_

I am using FastVGICP and I faced with the same problem. Could you help me? matching. Sophus ensure failed in function 'Sophus::SO3<Scalar_, Options>::SO3(const Transformation&) [with Scalar_ = float; int Options = 0; Sophus::SO3<Scalar_, Options>::Transformation = Eigen::Matrix<float, 3, 3>]', file '/..../src/fast_gicp/thirdparty/Sophus/sophus/so3.hpp', line 473. I got this message and the system is terminated.

**Comment by cdb0y511** [comment]
I meet this problem too. But you may avoid it. In my experience, it happens when the point clouds have little overlap or wrong initial guess. Anyway I think it means failed to get a proper solution. So when this happens, means track failed.

**Comment by koide3** [comment]
Normalizing the rotation part of your initial guess before running registration would fix that error.
```cpp
Eigen::Matrix4f guess = ...;
guess.block<3, 3>(0, 0) = Eigen::Quaternionf(guess.block<3, 3>(0, 0)).normalized().toRotationMatrix();
```

**Comment by cdb0y511** [comment]
> ```c++
> guess.block<3, 3>(0, 0) = Eigen::Quaternionf(guess.block<3, 3>(0, 0)).normalized().toRotationMatrix();
> ```
Hi,  I use identity as init guess; it still happens occasionally. 

        Eigen::Matrix4f initial_guess = Eigen::Matrix4f::Identity();
        reg.align(*tmpCloud, initial_guess);

optimize fail? maybe.

**Comment by koide3** [comment]
Can you check if putting normalization code just below the following line would help?

https://github.com/SMRT-AIST/fast_gicp/blob/8e0d2cfde3bf1fc2a9d7f2851ce31d3ee8be6197/include/fast_gicp/gicp/impl/fast_gicp_impl.hpp#L138

```cpp
    // normalize x1_
    x1_.linear() = Eigen::Quaternionf(x1_.linear()).normalized().toRotationMatrix();
```

**Comment by gulfemakpinar** [comment]
> Normalizing the rotation part of your initial guess before running registration would fix that error.
> 
> ```c++
> Eigen::Matrix4f guess = ...;
> guess.block<3, 3>(0, 0) = Eigen::Quaternionf(guess.block<3, 3>(0, 0)).normalized().toRotationMatrix();
> ```

Actually, I didn't really understand where I should add this code. If you could write it like above,  it would be great.

**Comment by koide3** [comment]
Thanks.  Please try to put the following code [here](https://github.com/SMRT-AIST/fast_gicp/blob/8e0d2cfde3bf1fc2a9d7f2851ce31d3ee8be6197/include/fast_gicp/gicp/impl/fast_gicp_impl.hpp#L138)

```cpp
Eigen::Isometry3f x1_ = delta_.inverse() * x0_;
x1_.linear() = Eigen::Quaternionf(x1_.linear()).normalized().toRotationMatrix();
```

**Comment by gulfemakpinar** [comment]
It still gives the same error.

**Comment by koide3** [comment]
Thanks for your coorperation. The cause is probably the unstable optimization as you said. In the current implementation, it uses a naive GN optimizer that can be unreliable when the initial guess is far from the true solution. I'll implement a more robust LM optimizer in next weeks.

**Comment by gulfemakpinar** [comment]
Thank you for you effort and help. I’ll wait.

**Comment by gulfemakpinar** [comment]
thanks. I'll try and share the results.

**Comment by gulfemakpinar** [comment]
I tried it and now it gives another error which is 
_**[pcl::KdTreeFLANN::setInputCloud] Cannot create a KDTree with an empty input cloud!**
Applying surface meshing...Using surface method: gp3 ...
**[pcl::KdTreeFLANN::setInputCloud] Cannot create a KDTree with an empty input cloud!**_

**Comment by koide3** [comment]
@gulfemakpinar 
I pushed updated implementation of FastGICP to ```devel``` branch. The updated code uses a more robust LM optimizer and avoids ```SO3::log()``` to prevent the non-orthogonal R error. I would be glad if you could check if it works well in your environment at your convenience.

**Comment by cdb0y511** [comment]
> @gulfemakpinar 
> I pushed updated implementation of FastGICP to ```devel``` branch. The updated code uses a more robust LM optimizer and avoids ```SO3::log()``` to prevent the non-orthogonal R error. I would be glad if you could check if it works well in your environment at your convenience.

Hi, I find it works perfectly on cpu version. No more  SO3 errors again.but cuda version still meet this problem. I think cuda version still use  gauss newton .Any schedule to fix the cuda version?

**Comment by koide3** [comment]
@cdb0y511  Thanks for testing it. I gonna improve the optimization of the cuda version as well in next week.

**Comment by gulfemakpinar** [comment]
Sorry for the late response. It works perfectly on my environment. Thank you.
