### ISSUE TITLE
The static assertion failed mistake!

### ISSUE THREAD

**Issue by sysuzyc** [SMRT-AIST/fast_gicp#3]
Hi, when I compile the project, the **static assertion** mistake happened!
![mistake](https://raw.githubusercontent.com/sysuzyc/Picture/master/Screenshot%20from%202020-02-20%2017-33-08.png)
The gcc version in my computer is **8.3.0**.
Could you please help me solve this problem?
Thanks!

**Comment by koide3** [comment]
Hi @sysuzyc ,
I couldn't reproduce the error with gcc-8 (Ubuntu 8.3.0-6ubuntu1~18.04.1). Can you provide more information so that I can produce the error?

**Comment by sysuzyc** [comment]
Hi, I have solved this problem. This problem just happened in Ubuntu 16.04. I have updated the Ubuntu version to 18.04. This problem didn't reproduce too.
Thanks for your help!
