### ISSUE TITLE
Question about the fitness change

### ISSUE THREAD

**Issue by cdb0y511** [SMRT-AIST/fast_gicp#34]
Hi,
I am curious about the recent update, especially the Benchmark part.
As I recall, the old ones for fgicp_mt vgicp_mt and so on are around 0.09.
However, the new one is backward to 0.2.
Caused by optimization method change from the gauss newton to Levenberg-Marquardt? That is GausNewton is better?
Or the parameters change?
After the recent update, I get a similar result, like the new benchmark.

The new one vs. the old one

target:17249[pts] source:17518[pts]
--- pcl_gicp ---
single:127.508[msec] 100times:12549.4[msec] fitness_score:0.204892
single:116.732[msec] 100times:10867.1[msec] fitness_score:0.204306
--- pcl_ndt ---
single:53.5904[msec] 100times:5467.16[msec] fitness_score:0.229616
single:52.8007[msec] 100times:5220.49[msec] fitness_score:0.226416
--- fgicp_st ---
single:111.324[msec] 100times:10662.7[msec] 100times_reuse:6794.59[msec] fitness_score:0.204379
single:110.343[msec] 100times:10651.2[msec] 100times_reuse:6962.1[msec] fitness_score:0.0922969
--- fgicp_mt ---
single:20.1602[msec] 100times:1585[msec] 100times_reuse:1017.74[msec] fitness_score:0.204412
single:24.3643[msec] 100times:2716.7[msec] 100times_reuse:1799.1[msec] fitness_score:0.0922969
--- vgicp_st ---
single:112.001[msec] 100times:7959.9[msec] 100times_reuse:4408.22[msec] fitness_score:0.204067
single:115.041[msec] 100times:8759.43[msec] 100times_reuse:4784.57[msec] fitness_score:0.0912174
--- vgicp_mt ---
single:18.1106[msec] 100times:1381[msec] 100times_reuse:806.53[msec] fitness_score:0.204067
single:19.705[msec] 100times:1963.74[msec] 100times_reuse:1044.29[msec] fitness_score:0.0912174
--- vgicp_cuda (parallel_kdtree) ---
single:15.9587[msec] 100times:1451.85[msec] 100times_reuse:695.48[msec] fitness_score:0.204061
single:16.1846[msec] 100times:1611.89[msec] 100times_reuse:779.65[msec] fitness_score:0.0709287
--- vgicp_cuda (gpu_bruteforce) ---
single:53.9113[msec] 100times:3463.5[msec] 100times_reuse:1703.41[msec] fitness_score:0.204049
single:49.7294[msec] 100times:3145.78[msec] 100times_reuse:1541.36[msec] fitness_score:0.0710122

**Comment by koide3** [comment]
This is because the old one had some bug and showed wrong fitness scores. I confirmed that the registration accuracy on KITTI is not changed by the optimizer update.

**Comment by cdb0y511** [comment]
Thanks, I am glad it was fixed.

**Comment by YangSiri** [comment]
> This is because the old one had some bug and showed wrong fitness scores. I confirmed that the registration accuracy on KITTI is not changed by the optimizer update.

Hi, @koide3 

I want to know more about the fitness score of the registration. I've read the codes behind it and know it estimates the average dist between aligned and target cloud. But it is weird that the score may be large though the result is good. So I wonder how exactly to measure the goodness of registration? For example if I need to filter out the bad result. Thanks.

Looking forward to your advice on that ;)

**Comment by koide3** [comment]
Actually, the fitness_score (RMSE between points) is not really a good metric to evaluate registration results, and this is why some extensions of ICP (e.g., normal ICP, GICP), which minimize the distance w.r.t. the object surface, perform better than the pure ICP. IMO, a reasonable way to assess the accuracy of registration results is evaluating the accuracy of estimated trajectories with the registration methods.

BTW, if you just need to find largely corrupted registration results, overlap rate can be used.

**Comment by YangSiri** [comment]
Thank you, @koide3 

Actually i want to incorporate it for loop closure verificaition. Overlap is also what i can came out.
