### ISSUE TITLE
Non-ROS library

### ISSUE THREAD

**Issue by HSarham** [SMRT-AIST/fast_gicp#4]
Hi,

I would like to use your code and would happily cite your work if I could use it. The only thing is that I am not familiar with ROS packages. Would it be possible for you to make a branch that creates a normal library without needing to work with ROS?

Thanks

**Comment by koide3** [comment]
Hi @HSarham ,
I used catkin for the ease of linking to ROS packages, but the code itself is ROS independent. So, you can just remove some catkin specific commands from CMakeLists, and then build the package with the standard cmake.

**Comment by koide3** [comment]
See the updated README for the installation guide for non-ROS platforms

**Comment by HSarham** [comment]
Thanks!
