### ISSUE TITLE
Compilation problems...

### ISSUE THREAD

**Issue by forest1998** [SMRT-AIST/fast_gicp#42]
Hi, Thank you for your great work.
But I'm stuck with a compilation problem.

- Errors
`
/home/swbot/slamware/slamros/forest_ws/SC_LeGO_LOAM_addGPS/devel/lib/libfast_gicp.so: undefined reference to `pcl::search::Search<pcl::PointXYZI>::getName() const'
collect2: error: ld returned 1 exit status
fast_gicp/CMakeFiles/gicp_align.dir/build.make:429: recipe for target '/home/swbot/slamware/slamros/forest_ws/SC_LeGO_LOAM_addGPS/devel/lib/fast_gicp/gicp_align' failed
make[2]: *** [/home/swbot/slamware/slamros/forest_ws/SC_LeGO_LOAM_addGPS/devel/lib/fast_gicp/gicp_align] Error 1
CMakeFiles/Makefile2:504: recipe for target 'fast_gicp/CMakeFiles/gicp_align.dir/all' failed
make[1]: *** [fast_gicp/CMakeFiles/gicp_align.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/home/swbot/slamware/slamros/forest_ws/SC_LeGO_LOAM_addGPS/devel/lib/libfast_gicp.so: undefined reference to `pcl::search::Search<pcl::PointXYZ>::getName() const'
/home/swbot/slamware/slamros/forest_ws/SC_LeGO_LOAM_addGPS/devel/lib/libfast_gicp.so: undefined reference to `pcl::search::Search<pcl::PointXYZI>::getName() const'
collect2: error: ld returned 1 exit status
fast_gicp/CMakeFiles/gicp_kitti.dir/build.make:429: recipe for target '/home/swbot/slamware/slamros/forest_ws/SC_LeGO_LOAM_addGPS/devel/lib/fast_gicp/gicp_kitti' failed
`

I tried adding #include <pcl/search/impl/search.hpp> to all the files in SRC directory.
But they don't seem to help.

- Environment
  Ubunto 18.04
  PCL 1.8

Sincerely.

**Comment by russellyq** [comment]
Hi I met a similar problem.

How did you solve it ?

Thanks in advance

**Comment by forest1998** [comment]
> Hi I met a similar problem.
> 
> How did you solve it ?
> 
> Thanks in advance
you can take a look at this link : https://blog.csdn.net/qq_47093464/article/details/117653955?spm=1001.2014.3001.5502
