### ISSUE TITLE
support point-to-point icp

### ISSUE THREAD

**Issue by xiaotaw** [SMRT-AIST/fast_gicp#46]
Does fast_gicp support point-to-point icp?

**Comment by koide3** [comment]
No, this package provides only distribution-to-distribution GICP algorithms.

**Comment by xiaotaw** [comment]
> No, this package provides only distribution-to-distribution GICP algorithms.

According to paper *Generalized-ICP*, between Eq. 2 and Eq. 3: 

> The standard ICP algorithm can be seen as a special case by setting: 
![](https://latex.codecogs.com/gif.latex?C_i^B=I)   
![](https://latex.codecogs.com/gif.latex?C_i^A=0)   

It seems quite easy to support standard point-to-point ICP.

**Comment by koide3** [comment]
If you want, you can set identity matrices, then it should be equivalent to P2P as written in the paper

https://github.com/SMRT-AIST/fast_gicp/blob/7798ac5afafdb58fc8f0c8794572a695b0c503a1/include/fast_gicp/gicp/fast_gicp.hpp#L52

**Comment by xiaotaw** [comment]
THX
