### ISSUE TITLE
Convergence comparison between NDT_OMP, GICP and VGICP

### ISSUE THREAD

**Issue by kinggreat24** [SMRT-AIST/fast_gicp#52]
Hi, @koide3 ,
  Thanks for sharing your great work to community, I have used these methods in LiDAR odometry and LiDAR loop closure detection modules. These methods are pretty well in LiDAR odometry especially for Fast-VGICP, but when I used these methods in   loop closure detection to calculate a initial transform form current LiDAR frame to candidate LiDAR map,  GICP and VGICP  output wrong results, and even not converged sometimes while NDT-omp can work normally. Have you compared the convergences between these methods, and do you have any ideas to improve convergences?

- Init source(red) and target(green) pointcloud 
![source_target_pcd](https://user-images.githubusercontent.com/30688557/116026453-61680400-a685-11eb-848c-ade23cfeff8d.png)
- gicp alignment results
![gicp](https://user-images.githubusercontent.com/30688557/116026554-8e1c1b80-a685-11eb-8e73-5a9c85836277.png)
- NDT alignment results
![NDT](https://user-images.githubusercontent.com/30688557/116026563-91afa280-a685-11eb-9081-48cc0db9614d.png)
- FAST-VGICP is not converged.

**Comment by Gatsby23** [comment]
> Hi, @koide3 , Thanks for sharing your great work to community, I have used these methods in LiDAR odometry and LiDAR loop closure detection modules. These methods are pretty well in LiDAR odometry especially for Fast-VGICP, but when I used these methods in loop closure detection to calculate a initial transform form current LiDAR frame to candidate LiDAR map, GICP and VGICP output wrong results, and even not converged sometimes while NDT-omp can work normally. Have you compared the convergences between these methods, and do you have any ideas to improve convergences?
> 
> * Init source(red) and target(green) pointcloud
>   ![source_target_pcd](https://user-images.githubusercontent.com/30688557/116026453-61680400-a685-11eb-848c-ade23cfeff8d.png)
> * gicp alignment results
>   ![gicp](https://user-images.githubusercontent.com/30688557/116026554-8e1c1b80-a685-11eb-8e73-5a9c85836277.png)
> * NDT alignment results
>   ![NDT](https://user-images.githubusercontent.com/30688557/116026563-91afa280-a685-11eb-9081-48cc0db9614d.png)
> * FAST-VGICP is not converged.

I'm interested in it. Do you know why ?

**Comment by kinggreat24** [comment]
> ICP-related methods are sensitive to initial parameters, I solved the problem by employing a feature-based registration method (TEASER++) to provide the initial transform, but it may take more time.
