### ISSUE TITLE
ndt_cuda.cu doesn't contain the getTransformationProbability() function

### ISSUE THREAD

**Issue by bill4u** [SMRT-AIST/fast_gicp#67]
hi koide, I have tested the autoware/ndt_gpu and want to integrate some autoware localization ideas into the hdl_graph_slam. I need the getTransformationProbability()  but in fast_gicp,  I cannot find something related. And suggestions to implement it ? @koide3 Thank a lot.

**Comment by nyxrobotics** [comment]
Hello, How did you deal with this problem?
