### ISSUE TITLE
Derivative verification!

### ISSUE THREAD

**Issue by nkliuhui** [SMRT-AIST/fast_gicp#78]
https://github.com/SMRT-AIST/fast_gicp/blob/7798ac5afafdb58fc8f0c8794572a695b0c503a1/include/fast_gicp/gicp/impl/fast_vgicp_impl.hpp#L157

I have some questions about the derivative of the rotating part. The code in the link means "skewd(Ra + t)". Should it be "skewd (Ra)"?

**Comment by koide3** [comment]
Hi @nkliuhui,
Please refer to https://github.com/SMRT-AIST/fast_gicp/issues/20#issuecomment-1017108211

**Comment by nkliuhui** [comment]
I see. Thank you!
