### ISSUE TITLE
Bug in FastVGICPCudaCore::calculate_target_covariances

### ISSUE THREAD

**Issue by HSarham** [SMRT-AIST/fast_gicp#9]
Hi, I noticed in the file fast_vgicp_cuda.cu, in the function:

void FastVGICPCudaCore::calculate_target_covariances(RegularizationMethod method) {
  assert(source_points && source_neighbors);

the assertion is wrong. It should assert the target points and neighbors not the source. I think it is just a copy and paste error. However it makes it impossible to set the target without setting the source first.

**Comment by koide3** [comment]
Hi @HSarham ,
Thank you for reporting the bug. I fixed it and updated the code.
