### ISSUE TITLE
Can't import python3 pygicp after installation

### ISSUE THREAD

**Issue by lichengqi0805** [SMRT-AIST/fast_gicp#93]
root@063a0cdb66f5:~/workspace/fast_gicp# python3
Python 3.8.0 (default, Dec  9 2021, 17:53:27)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
import pygicp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dynamic module does not define module export function (PyInit_pygicp)

**Comment by lichengqi0805** [comment]
Also, when I tried to install on focal with Cuda, pybind11/eigen.h seems to conflict with the Eigen I installed

fast_gicp/thirdparty/pybind11/include/pybind11/eigen.h:573:24: error: ‘MappedSparseMatrix’ is not a member of ‘Eigen’; did you mean ‘SparseMatrix’?
  573 |         value = Eigen::MappedSparseMatrix<Scalar, Type::Flags, StorageIndex>(
      |                        ^~~~~~~~~~~~~~~~~~
      |                        SparseMatrix

**Comment by mat0imaru** [comment]
how did you solve the problem? I'm having same problem as you. my python can't import pygicp.
