### ISSUE TITLE
Question: The relation between pcl registration function align() and computeTransformation()

### ISSUE THREAD

**Issue by wwtinwhu** [SMRT-AIST/fast_gicp#94]
Thank you for your excellent work! You've implemented some gicp variants on top of PCL's registration base class, great code!

I notice that you overide computeTransformation(). However, pcl registration class use align() to call, so , How does it work?

**Comment by koide3** [comment]
PCL::Registration::align() internally calls computeTransformation(). So, the actual registration process is written in the latter method.
